//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0907Ajax
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPM_Auto_Record_Log
    {
        public string Project_ID { get; set; }
        public string Part_Num { get; set; }
        public string DWG_Status { get; set; }
        public string DWG_Time { get; set; }
        public string Template_ID { get; set; }
        public string Template_Status { get; set; }
        public string Template_Time { get; set; }
        public string NC_For { get; set; }
        public string UG_PP { get; set; }
        public string PRT_HoleDia { get; set; }
        public string ToolIPNA { get; set; }
        public string ToolHolder { get; set; }
        public string Uipath_Status { get; set; }
        public string Uipath_Date { get; set; }
        public string NC_Status { get; set; }
        public string NC_Date { get; set; }
        public string MPMS_Status { get; set; }
        public string EMail { get; set; }
        public string EMail_Date { get; set; }
        public string NC_UploadError { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
