//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0908Datatable
{
    using System;
    using System.Collections.Generic;
    
    public partial class SPM_Routing_TemplateInfo
    {
        public string TempateID { get; set; }
        public string Routing { get; set; }
        public string Routing_SEQ { get; set; }
        public string Feature { get; set; }
        public string Value { get; set; }
    }
}
