//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0928DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class cnc_activity_log
    {
        public string Site { get; set; }
        public string pm_no { get; set; }
        public string Monitoring_Type { get; set; }
        public string Value { get; set; }
        public System.DateTime Act_Time { get; set; }
        public string workshop { get; set; }
        public string MC_Code { get; set; }
        public string Data_Source { get; set; }
    }
}
