//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _0928DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class CNC_Master_List
    {
        public string site { get; set; }
        public string pm_no { get; set; }
        public string Workshop { get; set; }
        public string MC_Code { get; set; }
        public string CNC_Type { get; set; }
        public string Monitoring { get; set; }
        public System.Guid rowguid { get; set; }
    }
}
